### ISSUE TITLE
Bug at Level 10

### ISSUE THREAD

**Issue by dmikushin** [EpocDotFr/tetris#1]
Hi @EpocDotFr ,

Great work and a lot of fun, thank you for this! And special thanks for the music!!

Unfortunately, I caught a freeze just after reaching level 10. The music continues to play, but the next block (I think the first one after level is incremented to 10) just freezed on the top. If I press the buttons, the block starts to move, an I can eventually land it down. But the block does not move by itself - it's stuck in zero gravity. I think there is a bug that Level 10 apparently became level 0. Could you please have a look?

![Screenshot from 2023-03-15 22-59-20](https://user-images.githubusercontent.com/5672874/225454252-468f545d-4c72-457f-a6d3-1cd6dc6b8d81.png)

**Comment by dmikushin** [comment]
There is still zero gravity on Level 11. I guess that's all, it will not accelerate again.

**Comment by EpocDotFr** [comment]
Hey Dmitry,

Woah this project is so old, didn't thought someone would ever submit an issue :D

> Great work and a lot of fun, thank you for this! And special thanks for the music!!

You're welcome, you can find credits about assets I used in [the README](https://github.com/EpocDotFr/tetris#credits).

Now regarding the bug, I'll take a look! Good job reaching level 10.

PS: I also made a [minesweeper game](https://github.com/EpocDotFr/minesweeper) ;)

**Comment by EpocDotFr** [comment]
You're indeed right: once you reach level 10, the calculation below evaluates to 0, which sets the "gravity" to zero: blocks are no longer falling.

```python
pygame.time.set_timer(settings.TETRIMINOS_FALLING_EVENT, settings.TETRIMINOS_INITIAL_FALLING_INTERVAL - self.level * settings.TETRIMINOS_FALLING_INTERVAL_DECREASE_STEP)
```

```python
pygame.time.set_timer(settings.TETRIMINOS_FALLING_EVENT, 1000 - 10 * 100)
```

**Comment by EpocDotFr** [comment]
Starting level 10, blocks will fall every 10 milliseconds until player loses.

You just have to `git pull` to get the fix. Happy playing!
